import { db } from './index.js';
import { serviceCategories } from './schema/categories.schema.js';
import {
  services,
  serviceOptions,
  serviceFields,
  serviceRules,
  servicePricingRules,
  serviceVersions,
} from './schema/services.schema.js';
import { providers, providerServices } from './schema/providers.schema.js';
import { eq } from 'drizzle-orm';

export async function initPhase4Catalog() {
  console.log('📦 [PHASE 4 CATALOG] Initializing full 26-service production catalog...');

  // 1. Ensure categories exist
  await db
    .insert(serviceCategories)
    .values([
      {
        id: 'cat_products',
        nameAr: 'منتجات واحتياجات',
        nameEn: 'Products & Needs',
        descriptionAr: 'توصيل أسطوانات الغاز، مياه الشرب، صهاريج المياه، الديزل، وشحن المركبات',
        descriptionEn: 'Delivery of gas cylinders, pure water, water tankers, diesel fuel, and EV charging',
        iconName: 'local_shipping_rounded',
        sortOrder: 1,
        isActive: true,
      },
      {
        id: 'cat_home_services',
        nameAr: 'خدمات منزلية',
        nameEn: 'Home Services',
        descriptionAr: 'صيانة الكهرباء، السباكة، التكييف، التدفئة، النجارة، والأقفال',
        descriptionEn: 'Electrical, plumbing, AC, heating, carpentry, and locks maintenance',
        iconName: 'home_repair_service_rounded',
        sortOrder: 2,
        isActive: true,
      },
      {
        id: 'cat_offers',
        nameAr: 'عروض وكوبونات',
        nameEn: 'Offers & Coupons',
        descriptionAr: 'خصومات حصرية وباقات توفير مميزة للمستخدمين والطلبات المتكررة',
        descriptionEn: 'Exclusive discounts, packages, and seasonal promotional coupons',
        iconName: 'local_offer_rounded',
        sortOrder: 3,
        isActive: true,
      },
    ])
    .onConflictDoNothing();

  // Find active providers to link services to
  const activeProviders = await db.select().from(providers).where(eq(providers.isActive, true));
  const defaultProviderId = activeProviders[0]?.id;

  const catalogDefinitions: any[] = [
    // 1. Gas (Existing Preserved)
    {
      service: {
        id: 'srv_gas_cylinder',
        categoryId: 'cat_products',
        nameAr: 'غاز',
        nameEn: 'Gas',
        descriptionAr: 'توصيل أسطوانات الغاز المنزلية مع الفحص الفوري لصمام الأمان والسلامة العامة',
        descriptionEn: 'Home delivery of certified LPG gas cylinders with on-site safety regulator inspection',
        type: 'delivery_product',
        basePrice: '7.00',
        unitAr: 'أسطوانة',
        unitEn: 'cylinder',
        isLaborOnly: false,
        serviceMode: 'product_variant',
        status: 'published',
        isPublished: true,
        isActive: true,
        currentVersion: 1,
      },
      options: [
        {
          id: 'opt_gas_12_5kg',
          nameAr: 'تبديل أسطوانة غاز 12.5 كغم',
          nameEn: '12.5kg Gas Cylinder Refill',
          optionType: 'variant',
          size: '12.5 kg',
          price: '7.00',
          unitAr: 'أسطوانة',
          unitEn: 'cylinder',
          sortOrder: 1,
          isActive: true,
        },
        {
          id: 'opt_gas_new_cylinder',
          nameAr: 'شراء أسطوانة جديدة معبأة',
          nameEn: 'New Cylinder with Gas',
          optionType: 'variant',
          size: '12.5 kg',
          price: '45.00',
          unitAr: 'أسطوانة',
          unitEn: 'cylinder',
          sortOrder: 2,
          isActive: true,
        },
        {
          id: 'opt_gas_regulator',
          nameAr: 'منظم وصمام أمان أصلي',
          nameEn: 'Certified Safety Regulator',
          optionType: 'addon',
          price: '8.00',
          unitAr: 'قطعة',
          unitEn: 'piece',
          sortOrder: 3,
          isActive: true,
        },
      ],
      fields: [],
      rules: [],
      pricingRules: [],
    },

    // 2. Water (Multi-variant products/sizes)
    {
      service: {
        id: 'srv_water_delivery',
        categoryId: 'cat_products',
        nameAr: 'مياه شرب نقية وصهاريج',
        nameEn: 'Pure Water & Tankers',
        descriptionAr: 'توصيل قوارير مياه الشرب النقية، الكاسات، وصهاريج المياه المعقمة للمنازل والمباني',
        descriptionEn: 'Delivery of purified drinking water, cups, bottles, 19L gallons, and water tankers',
        type: 'delivery_product',
        basePrice: '1.50',
        unitAr: 'قارورة / صهريج',
        unitEn: 'gallon / tanker',
        isLaborOnly: false,
        serviceMode: 'product_variant',
        status: 'published',
        isPublished: true,
        isActive: true,
        currentVersion: 1,
      },
      options: [
        {
          id: 'opt_water_19l_refill',
          nameAr: 'تبديل قارورة مياه 19 لتر',
          nameEn: '19L Gallon Refill',
          optionType: 'variant',
          size: '19 L',
          price: '1.50',
          unitAr: 'قارورة',
          unitEn: 'gallon',
          sortOrder: 1,
          isActive: true,
        },
        {
          id: 'opt_water_19l_new',
          nameAr: 'شراء قارورة 19 لتر جديدة معبأة',
          nameEn: 'New 19L Gallon with Water',
          optionType: 'variant',
          size: '19 L',
          price: '6.00',
          unitAr: 'قارورة',
          unitEn: 'gallon',
          sortOrder: 2,
          isActive: true,
        },
        {
          id: 'opt_water_cups_pack',
          nameAr: 'كرتونة كاسات مياه معقمة (40 كاسة)',
          nameEn: 'Water Cups Pack (40 cups)',
          optionType: 'variant',
          size: '40 x 200ml',
          price: '3.00',
          unitAr: 'كرتونة',
          unitEn: 'pack',
          sortOrder: 3,
          isActive: true,
        },
        {
          id: 'opt_water_bottles_half_liter',
          nameAr: 'كرتونة مطرات 0.5 لتر (12 عبوة)',
          nameEn: '0.5L Bottles Pack (12 bottles)',
          optionType: 'variant',
          size: '12 x 0.5L',
          price: '2.50',
          unitAr: 'كرتونة',
          unitEn: 'pack',
          sortOrder: 4,
          isActive: true,
        },
        {
          id: 'opt_water_bottles_1_5_liter',
          nameAr: 'كرتونة مطرات 1.5 لتر (6 عبوات)',
          nameEn: '1.5L Bottles Pack (6 bottles)',
          optionType: 'variant',
          size: '6 x 1.5L',
          price: '2.50',
          unitAr: 'كرتونة',
          unitEn: 'pack',
          sortOrder: 5,
          isActive: true,
        },
        {
          id: 'opt_water_tanker_2m3',
          nameAr: 'صهريج مياه نقي 2 متر مكعب (2000 لتر)',
          nameEn: '2m³ Pure Water Tanker',
          optionType: 'variant',
          size: '2m³',
          price: '18.00',
          unitAr: 'صهريج',
          unitEn: 'tanker',
          sortOrder: 6,
          isActive: true,
        },
        {
          id: 'opt_water_tanker_4m3',
          nameAr: 'صهريج مياه نقي 4 متر مكعب (4000 لتر)',
          nameEn: '4m³ Pure Water Tanker',
          optionType: 'variant',
          size: '4m³',
          price: '32.00',
          unitAr: 'صهريج',
          unitEn: 'tanker',
          sortOrder: 7,
          isActive: true,
        },
      ],
      fields: [],
      rules: [],
      pricingRules: [],
    },

    // 3. Diesel / Boiler Fuel
    {
      service: {
        id: 'srv_diesel_fuel',
        categoryId: 'cat_products',
        nameAr: 'ديزل تدفئة وبويلرات',
        nameEn: 'Heating Diesel Fuel',
        descriptionAr: 'تزويد محروقات الديزل للتدفئة والبويلرات مع عدادات إلكترونية معايرة ومعتمدة',
        descriptionEn: 'High grade heating diesel with calibrated digital meters for home boilers',
        type: 'delivery_product',
        basePrice: '0.00',
        unitAr: 'لتر',
        unitEn: 'liter',
        minOrderValue: '150.00',
        maxOrderValue: '1500.00',
        isLaborOnly: false,
        serviceMode: 'dynamic_form',
        status: 'published',
        isPublished: true,
        isActive: true,
        currentVersion: 1,
      },
      options: [],
      fields: [
        {
          key: 'liters_count',
          labelAr: 'كمية الديزل المطلوبة (باللتر)',
          labelEn: 'Required Diesel (Liters)',
          fieldType: 'number',
          min: '200',
          max: '2000',
          step: '50',
          defaultValue: 500,
          unitAr: 'لتر',
          unitEn: 'Liters',
          isRequired: true,
          sortOrder: 1,
        },
        {
          key: 'tank_location',
          labelAr: 'موقع خزان الديزل',
          labelEn: 'Tank Location',
          fieldType: 'select',
          options: [
            { id: 'ground', labelAr: 'أرضي / الحديقة', labelEn: 'Ground / Garden', value: 'ground' },
            { id: 'basement', labelAr: 'تسوية / الكراج', labelEn: 'Basement / Garage', value: 'basement' },
            { id: 'roof', labelAr: 'السطح', labelEn: 'Roof', value: 'roof' },
          ],
          defaultValue: 'ground',
          isRequired: true,
          sortOrder: 2,
        },
        {
          key: 'meter_inspection',
          labelAr: 'طلب فحص تصفير العداد الإلكتروني قبل التعبئة',
          labelEn: 'Request digital meter zeroing inspection',
          fieldType: 'toggle',
          defaultValue: true,
          isRequired: false,
          sortOrder: 3,
        },
      ],
      rules: [],
      pricingRules: [
        {
          ruleType: 'field_multiplier',
          titleAr: 'سعر لتر الديزل',
          titleEn: 'Diesel Price per Liter',
          targetField: 'liters_count',
          calculationFormula: { ratePerUnit: 0.75, baseThreshold: 0 },
          sortOrder: 1,
        },
      ],
    },

    // 4. Plumbing (Starting from 5 JOD)
    {
      service: {
        id: 'srv_plumbing',
        categoryId: 'cat_home_services',
        nameAr: 'سباكة وتمديدات صحية',
        nameEn: 'Plumbing & Sanitary Services',
        descriptionAr: 'صيانة ومعالجة تسريبات المياه، تركيب المغاسل، الحنفيات، كشف الأعطال وتصليح الخطوط',
        descriptionEn: 'Leak repair, sanitary fixtures, faucets, drain unclogging and pipe installations',
        type: 'home_service',
        basePrice: '5.00',
        unitAr: 'أجرة معاينة/يد',
        unitEn: 'inspection/labor fee',
        startingPriceLabelAr: 'يبدأ من',
        startingPriceLabelEn: 'Starting from',
        disclaimerAr: 'السعر الظاهر هو أجرة اليد/الخدمة الأساسية فقط، ولا يشمل قطع الغيار أو المواد أو المعدات أو أي أعمال إضافية قد تكون مطلوبة.',
        disclaimerEn: 'The displayed price is the labor/service starting fee only. It does not include spare parts, materials, equipment, or additional work that may be required.',
        isLaborOnly: true,
        requiresQuotation: true,
        serviceMode: 'labor_inspection',
        status: 'published',
        isPublished: true,
        isActive: true,
        currentVersion: 1,
      },
      options: [],
      fields: [
        {
          key: 'issue_category',
          labelAr: 'نوع العطل أو العمل المطلوب',
          labelEn: 'Issue Category',
          fieldType: 'select',
          options: [
            { id: 'leak', labelAr: 'كشف وإصلاح تسريب مياه', labelEn: 'Water Leak Repair', value: 'leak' },
            { id: 'faucet_toilet', labelAr: 'صيانة / تركيب حنفيات ومغاسل ومراحيض', labelEn: 'Faucets & Toilets', value: 'faucet_toilet' },
            { id: 'drain', labelAr: 'تسليك مجاري وانسدادات', labelEn: 'Drain Unclogging', value: 'drain' },
            { id: 'water_heater_pipes', labelAr: 'تمديدات وصيانة خطوط السخان والمضخة', labelEn: 'Water Heater/Pump Pipes', value: 'water_heater_pipes' },
            { id: 'other', labelAr: 'أعمال سباكة أخرى', labelEn: 'Other Plumbing', value: 'other' },
          ],
          defaultValue: 'leak',
          isRequired: true,
          sortOrder: 1,
        },
        {
          key: 'problem_description',
          labelAr: 'وصف المشكلة بالتفصيل',
          labelEn: 'Problem Description',
          fieldType: 'textarea',
          placeholderAr: 'يرجى وصف المشكلة ومكانها بدقة لمساعدة الفني في تجهيز القطع والمعدات...',
          placeholderEn: 'Describe the problem in detail...',
          isRequired: true,
          sortOrder: 2,
        },
        {
          key: 'problem_photos',
          labelAr: 'صور المشكلة (اختياري)',
          labelEn: 'Photos of the problem (optional)',
          fieldType: 'image_upload',
          isRequired: false,
          sortOrder: 3,
        },
        {
          key: 'preferred_time',
          labelAr: 'الوقت المفضل للزيارة',
          labelEn: 'Preferred Visit Time',
          fieldType: 'select',
          options: [
            { id: 'morning', labelAr: 'صباحاً (9:00 ص - 1:00 م)', labelEn: 'Morning (9AM - 1PM)', value: 'morning' },
            { id: 'afternoon', labelAr: 'ظهراً (1:00 م - 5:00 م)', labelEn: 'Afternoon (1PM - 5PM)', value: 'afternoon' },
            { id: 'evening', labelAr: 'مساءً (5:00 م - 9:00 م)', labelEn: 'Evening (5PM - 9PM)', value: 'evening' },
          ],
          defaultValue: 'morning',
          isRequired: false,
          sortOrder: 4,
        },
      ],
      rules: [],
      pricingRules: [
        {
          ruleType: 'base',
          titleAr: 'أجرة المعاينة واليد الأساسية',
          titleEn: 'Base Starting Labor Fee',
          calculationFormula: { fixedAmount: 5.00 },
          sortOrder: 1,
        },
      ],
    },

    // 5. Electricity (Starting from 5 JOD)
    {
      service: {
        id: 'srv_electricity',
        categoryId: 'cat_home_services',
        nameAr: 'كهرباء وتمديدات منزلية',
        nameEn: 'Electrical & Wiring Services',
        descriptionAr: 'صيانة القواطع الكهربائية، كشف الشورت، تمديد خطوط، تركيب إنارة وثريات، وحل الأعطال',
        descriptionEn: 'Circuit breaker repair, electrical short circuit troubleshooting, lighting and chandeliers',
        type: 'home_service',
        basePrice: '5.00',
        unitAr: 'أجرة معاينة/يد',
        unitEn: 'inspection/labor fee',
        startingPriceLabelAr: 'يبدأ من',
        startingPriceLabelEn: 'Starting from',
        disclaimerAr: 'السعر الظاهر هو أجرة اليد/الخدمة الأساسية فقط، ولا يشمل قطع الغيار أو المواد أو المعدات أو أي أعمال إضافية قد تكون مطلوبة.',
        disclaimerEn: 'The displayed price is the labor/service starting fee only. It does not include spare parts, materials, equipment, or additional work that may be required.',
        isLaborOnly: true,
        requiresQuotation: true,
        serviceMode: 'labor_inspection',
        status: 'published',
        isPublished: true,
        isActive: true,
        currentVersion: 1,
      },
      options: [],
      fields: [
        {
          key: 'issue_type',
          labelAr: 'نوع العطل الكهربائي',
          labelEn: 'Electrical Issue Type',
          fieldType: 'select',
          options: [
            { id: 'short_circuit', labelAr: 'انقطاع كهرباء أو شورت كهربائي', labelEn: 'Short Circuit / Power Outage', value: 'short_circuit' },
            { id: 'breaker_box', labelAr: 'عطل في لوحة القواطع الرئيسية', labelEn: 'Breaker Box Malfunction', value: 'breaker_box' },
            { id: 'lighting', labelAr: 'تركيب وصيانة ثريات وإنارة', labelEn: 'Lighting & Chandeliers', value: 'lighting' },
            { id: 'plugs_sockets', labelAr: 'تصليح أو تمديد مفاتيح وأباريز', labelEn: 'Plugs & Sockets Wiring', value: 'plugs_sockets' },
            { id: 'other', labelAr: 'أعمال كهربائية أخرى', labelEn: 'Other Electrical', value: 'other' },
          ],
          defaultValue: 'short_circuit',
          isRequired: true,
          sortOrder: 1,
        },
        {
          key: 'problem_description',
          labelAr: 'وصف العطل بالتفصيل',
          labelEn: 'Problem Description',
          fieldType: 'textarea',
          placeholderAr: 'صف العطل الكهربائي والأعراض الظاهرة...',
          placeholderEn: 'Describe the electrical problem...',
          isRequired: true,
          sortOrder: 2,
        },
        {
          key: 'problem_photos',
          labelAr: 'صور لوحة القواطع أو العطل (اختياري)',
          labelEn: 'Photos of the issue (optional)',
          fieldType: 'image_upload',
          isRequired: false,
          sortOrder: 3,
        },
        {
          key: 'is_emergency',
          labelAr: 'طلب زيارة طوارئ عاجلة (+10 د.أ)',
          labelEn: 'Request emergency urgent visit (+10 JOD)',
          fieldType: 'toggle',
          defaultValue: false,
          isRequired: false,
          sortOrder: 4,
        },
      ],
      rules: [],
      pricingRules: [
        {
          ruleType: 'base',
          titleAr: 'أجرة اليد الأساسية',
          titleEn: 'Base Starting Labor Fee',
          calculationFormula: { fixedAmount: 5.00 },
          sortOrder: 1,
        },
        {
          ruleType: 'conditional_formula',
          titleAr: 'رسوم زيارة طوارئ عاجلة',
          titleEn: 'Emergency Urgent Visit Surcharge',
          condition: {
            operator: 'AND',
            expressions: [{ field: 'is_emergency', op: 'eq', value: true }],
          },
          calculationFormula: { fixedAmount: 10.00 },
          sortOrder: 2,
        },
      ],
    },

    // 6. Air Conditioning & Cooling (Starting from 5 JOD)
    {
      service: {
        id: 'srv_ac_cooling',
        categoryId: 'cat_home_services',
        nameAr: 'صيانة وتكييف وتبريد',
        nameEn: 'AC & Air Conditioning',
        descriptionAr: 'صيانة مكيفات السبلت والمركزي، تنظيف الفلاتر والوحدات، شحن غاز، وفحص التبريد',
        descriptionEn: 'Split and central AC maintenance, gas refill, filter cleaning and cooling repair',
        type: 'home_service',
        basePrice: '5.00',
        unitAr: 'أجرة معاينة/يد',
        unitEn: 'inspection/labor fee',
        startingPriceLabelAr: 'يبدأ من',
        startingPriceLabelEn: 'Starting from',
        disclaimerAr: 'السعر الظاهر هو أجرة اليد/الخدمة الأساسية فقط، ولا يشمل قطع الغيار أو المواد أو المعدات أو أي أعمال إضافية قد تكون مطلوبة.',
        disclaimerEn: 'The displayed price is the labor/service starting fee only. It does not include spare parts, materials, equipment, or additional work that may be required.',
        isLaborOnly: true,
        requiresQuotation: true,
        serviceMode: 'labor_inspection',
        status: 'published',
        isPublished: true,
        isActive: true,
        currentVersion: 1,
      },
      options: [],
      fields: [
        {
          key: 'ac_type',
          labelAr: 'نوع المكيف',
          labelEn: 'AC Type',
          fieldType: 'select',
          options: [
            { id: 'split', labelAr: 'مكيف سبلت جداري (Split)', labelEn: 'Split Wall Unit', value: 'split' },
            { id: 'central', labelAr: 'تكييف مركزي (Central AC)', labelEn: 'Central AC System', value: 'central' },
            { id: 'standing', labelAr: 'مكيف عمودي / كونسول', labelEn: 'Floor Standing Unit', value: 'standing' },
          ],
          defaultValue: 'split',
          isRequired: true,
          sortOrder: 1,
        },
        {
          key: 'ac_units_count',
          labelAr: 'عدد المكيفات',
          labelEn: 'AC Units Count',
          fieldType: 'counter',
          min: '1',
          max: '10',
          step: '1',
          defaultValue: 1,
          isRequired: true,
          sortOrder: 2,
        },
        {
          key: 'service_needed',
          labelAr: 'الخدمة المطلوبة',
          labelEn: 'Required Service',
          fieldType: 'select',
          options: [
            { id: 'inspection', labelAr: 'فحص وتشخيص عطل تبريد', labelEn: 'Cooling Diagnosis', value: 'inspection' },
            { id: 'gas_refill', labelAr: 'تعبئة وشحن غاز تبريد', labelEn: 'Refrigerant Gas Refill', value: 'gas_refill' },
            { id: 'deep_cleaning', labelAr: 'غسيل وتنظيف الفلاتر والوحدة الخارجية', labelEn: 'Deep Unit Wash', value: 'deep_cleaning' },
            { id: 'install_dismantle', labelAr: 'فك ونقل أو تركيب مكيف جديد', labelEn: 'AC Installation / Move', value: 'install_dismantle' },
          ],
          defaultValue: 'inspection',
          isRequired: true,
          sortOrder: 3,
        },
        {
          key: 'problem_description',
          labelAr: 'وصف المشكلة',
          labelEn: 'Problem Description',
          fieldType: 'textarea',
          isRequired: false,
          sortOrder: 4,
        },
      ],
      rules: [],
      pricingRules: [
        {
          ruleType: 'base',
          titleAr: 'أجرة اليد الأساسية',
          titleEn: 'Starting Labor Fee',
          calculationFormula: { fixedAmount: 5.00 },
          sortOrder: 1,
        },
      ],
    },

    // 7. Home Cleaning (With custom packages like 4 workers = 17 JOD)
    {
      service: {
        id: 'srv_home_cleaning',
        categoryId: 'cat_home_services',
        nameAr: 'نظافة منزلية وباقات عاملات',
        nameEn: 'Home Cleaning & Maid Packages',
        descriptionAr: 'تنظيف شامل للمنازل، تعقيم، باقات بالساعة مع خيارات تحديد عدد وجنس العمال ومواد التنظيف',
        descriptionEn: 'Deep and standard home cleaning, hourly maid packages with customizable worker preferences',
        type: 'home_service',
        basePrice: '5.00',
        unitAr: 'عامل / 4 ساعات',
        unitEn: 'worker / 4 hours',
        isLaborOnly: false,
        serviceMode: 'package_bundle',
        status: 'published',
        isPublished: true,
        isActive: true,
        currentVersion: 1,
      },
      options: [
        {
          id: 'opt_clean_pkg_1',
          nameAr: 'باقة عامل واحد (4 ساعات)',
          nameEn: '1 Worker Package (4h)',
          optionType: 'package',
          price: '5.00',
          packageWorkerCount: 1,
          packageDurationHours: '4.00',
          unitAr: 'باقة',
          unitEn: 'package',
          sortOrder: 1,
          isActive: true,
        },
        {
          id: 'opt_clean_pkg_2',
          nameAr: 'باقة التوفير: 2 عاملات (4 ساعات)',
          nameEn: 'Saving Package: 2 Workers (4h)',
          optionType: 'package',
          price: '9.00',
          packageWorkerCount: 2,
          packageDurationHours: '4.00',
          unitAr: 'باقة',
          unitEn: 'package',
          sortOrder: 2,
          isActive: true,
        },
        {
          id: 'opt_clean_pkg_4',
          nameAr: 'باقة العائلة المميزة: 4 عاملات (4 ساعات)',
          nameEn: 'Family Package: 4 Workers (4h)',
          optionType: 'package',
          price: '17.00',
          packageWorkerCount: 4,
          packageDurationHours: '4.00',
          unitAr: 'باقة',
          unitEn: 'package',
          sortOrder: 3,
          isActive: true,
        },
        {
          id: 'opt_clean_pkg_6',
          nameAr: 'باقة الفيلا الكبرى: 6 عاملات (4 ساعات)',
          nameEn: 'Villa Package: 6 Workers (4h)',
          optionType: 'package',
          price: '24.00',
          packageWorkerCount: 6,
          packageDurationHours: '4.00',
          unitAr: 'باقة',
          unitEn: 'package',
          sortOrder: 4,
          isActive: true,
        },
      ],
      fields: [
        {
          key: 'workers_count',
          labelAr: 'عدد العاملين المطلوبين',
          labelEn: 'Number of Workers',
          fieldType: 'counter',
          min: '1',
          max: '8',
          step: '1',
          defaultValue: 1,
          isRequired: true,
          sortOrder: 1,
        },
        {
          key: 'worker_gender',
          labelAr: 'تفضيل جنس العاملين',
          labelEn: 'Worker Gender Preference',
          fieldType: 'radio',
          options: [
            { id: 'female', labelAr: 'عاملات إناث', labelEn: 'Female Maids', value: 'female' },
            { id: 'male', labelAr: 'عمال ذكور', labelEn: 'Male Workers', value: 'male' },
            { id: 'no_pref', labelAr: 'لا يوجد تفضيل محدد', labelEn: 'No Preference', value: 'no_pref' },
          ],
          defaultValue: 'female',
          isRequired: true,
          sortOrder: 2,
        },
        {
          key: 'cleaning_type',
          labelAr: 'نوع النظافة المطلوبة',
          labelEn: 'Cleaning Type',
          fieldType: 'select',
          options: [
            { id: 'standard', labelAr: 'تنظيف دوري عادي', labelEn: 'Standard Cleaning', value: 'standard' },
            { id: 'deep', labelAr: 'تنظيف عميق شامل (+5 د.أ)', labelEn: 'Deep Cleaning (+5 JOD)', value: 'deep', priceModifier: 5.0 },
            { id: 'post_construction', labelAr: 'تنظيف بعد التشطيب والدهان (+10 د.أ)', labelEn: 'Post Construction (+10 JOD)', value: 'post_construction', priceModifier: 10.0 },
          ],
          defaultValue: 'standard',
          isRequired: true,
          sortOrder: 3,
        },
        {
          key: 'bring_cleaning_materials',
          labelAr: 'طلب توفير مواد التنظيف والمعدات من الشركة (+4 د.أ)',
          labelEn: 'Company provides cleaning supplies (+4 JOD)',
          fieldType: 'toggle',
          defaultValue: false,
          isRequired: false,
          sortOrder: 4,
        },
      ],
      rules: [],
      pricingRules: [
        {
          ruleType: 'field_multiplier',
          titleAr: 'أجرة العمال',
          titleEn: 'Workers Fee',
          targetField: 'workers_count',
          calculationFormula: { ratePerUnit: 5.00, baseThreshold: 0 },
          sortOrder: 1,
        },
        {
          ruleType: 'conditional_formula',
          titleAr: 'رسوم توفير مواد ومعدات التنظيف',
          titleEn: 'Cleaning Supplies Fee',
          condition: {
            operator: 'AND',
            expressions: [{ field: 'bring_cleaning_materials', op: 'eq', value: true }],
          },
          calculationFormula: { fixedAmount: 4.00 },
          sortOrder: 2,
        },
      ],
    },

    // 8. Carpentry / Furniture Assembly (Starting from 5 JOD)
    {
      service: {
        id: 'srv_carpentry',
        categoryId: 'cat_home_services',
        nameAr: 'نجارة وفك وتركيب أثاث',
        nameEn: 'Carpentry & Furniture Assembly',
        descriptionAr: 'فك وتركيب غرف النوم، المطابخ، تصليح الأبواب والخزائن، وتركيب أثاث إيكيا',
        descriptionEn: 'Furniture assembly, Ikea assembly, door repair, closets and custom carpentry',
        type: 'home_service',
        basePrice: '5.00',
        unitAr: 'أجرة معاينة/يد',
        unitEn: 'inspection/labor fee',
        startingPriceLabelAr: 'يبدأ من',
        startingPriceLabelEn: 'Starting from',
        disclaimerAr: 'السعر الظاهر هو أجرة اليد/الخدمة الأساسية فقط، ولا يشمل قطع الغيار أو المواد أو المعدات أو أي أعمال إضافية قد تكون مطلوبة.',
        disclaimerEn: 'The displayed price is the labor/service starting fee only. It does not include spare parts, materials, equipment, or additional work that may be required.',
        isLaborOnly: true,
        requiresQuotation: true,
        serviceMode: 'labor_inspection',
        status: 'published',
        isPublished: true,
        isActive: true,
        currentVersion: 1,
      },
      options: [],
      fields: [
        {
          key: 'carpentry_service',
          labelAr: 'نوع عمل النجارة',
          labelEn: 'Carpentry Service Type',
          fieldType: 'select',
          options: [
            { id: 'furniture_assembly', labelAr: 'تركيب أثاث جديد / إيكيا', labelEn: 'New Furniture / Ikea Assembly', value: 'furniture_assembly' },
            { id: 'door_repair', labelAr: 'صيانة وتعديل أبواب وحلق خشب', labelEn: 'Door Repair & Adjustment', value: 'door_repair' },
            { id: 'closet_drawers', labelAr: 'تصليح سحابات أدراج وخزائن', labelEn: 'Closet & Drawer Rails Repair', value: 'closet_drawers' },
            { id: 'kitchen_wood', labelAr: 'صيانة خزائن مطبخ', labelEn: 'Kitchen Cabinets Maintenance', value: 'kitchen_wood' },
          ],
          defaultValue: 'furniture_assembly',
          isRequired: true,
          sortOrder: 1,
        },
        {
          key: 'problem_description',
          labelAr: 'تفاصيل العمل المطلوب',
          labelEn: 'Job Details Description',
          fieldType: 'textarea',
          isRequired: true,
          sortOrder: 2,
        },
        {
          key: 'furniture_photos',
          labelAr: 'صور الأثاث أو القطع المطلوب صيانتها (اختياري)',
          labelEn: 'Photos (optional)',
          fieldType: 'image_upload',
          isRequired: false,
          sortOrder: 3,
        },
      ],
      rules: [],
      pricingRules: [
        {
          ruleType: 'base',
          titleAr: 'أجرة اليد الأساسية',
          titleEn: 'Starting Labor Fee',
          calculationFormula: { fixedAmount: 5.00 },
          sortOrder: 1,
        },
      ],
    },

    // 9. General Home Maintenance (Starting from 5 JOD)
    {
      service: {
        id: 'srv_general_maintenance',
        categoryId: 'cat_home_services',
        nameAr: 'صيانة منزلية عامة وشاملة',
        nameEn: 'General Home Maintenance',
        descriptionAr: 'معالجة الأعطال المنزلية المتنوعة، الفحص الشامل للبيت، والإصلاحات السريعة',
        descriptionEn: 'General handyman, home repairs, multi-skill troubleshooting and fixes',
        type: 'home_service',
        basePrice: '5.00',
        unitAr: 'أجرة معاينة/يد',
        unitEn: 'inspection/labor fee',
        startingPriceLabelAr: 'يبدأ من',
        startingPriceLabelEn: 'Starting from',
        disclaimerAr: 'السعر الظاهر هو أجرة اليد/الخدمة الأساسية فقط، ولا يشمل قطع الغيار أو المواد أو المعدات أو أي أعمال إضافية قد تكون مطلوبة.',
        disclaimerEn: 'The displayed price is the labor/service starting fee only. It does not include spare parts, materials, equipment, or additional work that may be required.',
        isLaborOnly: true,
        requiresQuotation: true,
        serviceMode: 'labor_inspection',
        status: 'published',
        isPublished: true,
        isActive: true,
        currentVersion: 1,
      },
      options: [],
      fields: [
        {
          key: 'problem_description',
          labelAr: 'شرح تفصيلي لأعمال الصيانة المطلوبة',
          labelEn: 'Detailed Maintenance Description',
          fieldType: 'textarea',
          isRequired: true,
          sortOrder: 1,
        },
        {
          key: 'photos',
          labelAr: 'صور توضيحية للأعمال (اختياري)',
          labelEn: 'Photos (optional)',
          fieldType: 'image_upload',
          isRequired: false,
          sortOrder: 2,
        },
      ],
      rules: [],
      pricingRules: [
        {
          ruleType: 'base',
          titleAr: 'أجرة اليد الأساسية',
          titleEn: 'Starting Labor Fee',
          calculationFormula: { fixedAmount: 5.00 },
          sortOrder: 1,
        },
      ],
    },

    // 10. Water Heaters (Product + Installation)
    {
      service: {
        id: 'srv_water_heaters',
        categoryId: 'cat_home_services',
        nameAr: 'سخانات مياه وكيزر وبويلرات',
        nameEn: 'Water Heaters & Boilers',
        descriptionAr: 'كتالوج سخانات مياه كهرباء وغاز مع خيار التركيب الفوري وضمان التشغيل',
        descriptionEn: 'Electric & gas water heater product catalog with professional installation',
        type: 'home_service',
        basePrice: '85.00',
        unitAr: 'سخان',
        unitEn: 'heater',
        isLaborOnly: false,
        serviceMode: 'product_installation',
        status: 'published',
        isPublished: true,
        isActive: true,
        currentVersion: 1,
      },
      options: [
        {
          id: 'opt_heater_50l_electric',
          nameAr: 'سخان كهرباء 50 لتر إيطالي (Ariston)',
          nameEn: '50L Electric Water Heater (Ariston)',
          optionType: 'product',
          brand: 'Ariston',
          size: '50 L',
          price: '85.00',
          installationPrice: '25.00',
          unitAr: 'سخان',
          unitEn: 'heater',
          descriptionAr: 'سخان ستانلس ستيل معزول حرارياً موفر للطاقة بضمان سنتين',
          sortOrder: 1,
          isActive: true,
        },
        {
          id: 'opt_heater_80l_electric',
          nameAr: 'سخان كهرباء 80 لتر فرنسي (Atlantic)',
          nameEn: '80L Electric Water Heater (Atlantic)',
          optionType: 'product',
          brand: 'Atlantic',
          size: '80 L',
          price: '110.00',
          installationPrice: '25.00',
          unitAr: 'سخان',
          unitEn: 'heater',
          descriptionAr: 'سخان عائلي سعة 80 لتر عالي التحمل',
          sortOrder: 2,
          isActive: true,
        },
        {
          id: 'opt_heater_10l_gas_instant',
          nameAr: 'كيزر غاز فوري 10 لتر ياباني (Rinnai)',
          nameEn: '10L Instant Gas Water Heater (Rinnai)',
          optionType: 'product',
          brand: 'Rinnai',
          size: '10 L/min',
          price: '95.00',
          installationPrice: '30.00',
          unitAr: 'سخان',
          unitEn: 'heater',
          descriptionAr: 'تسخين فوري فائق السرعة آمن مع حساس انقطاع الغاز',
          sortOrder: 3,
          isActive: true,
        },
      ],
      fields: [
        {
          key: 'include_installation',
          labelAr: 'إضافة خدمة التركيب وتمديد الوصلات وضمان التشغيل',
          labelEn: 'Include professional installation & test',
          fieldType: 'toggle',
          defaultValue: true,
          isRequired: false,
          sortOrder: 1,
        },
        {
          key: 'old_heater_removal',
          labelAr: 'طلب فك وتنزيل السخان القديم (+5 د.أ)',
          labelEn: 'Dismantle and remove old heater (+5 JOD)',
          fieldType: 'toggle',
          defaultValue: false,
          isRequired: false,
          sortOrder: 2,
        },
      ],
      rules: [],
      pricingRules: [
        {
          ruleType: 'conditional_formula',
          titleAr: 'أجرة فك السخان القديم',
          titleEn: 'Old Heater Removal Fee',
          condition: {
            operator: 'AND',
            expressions: [{ field: 'old_heater_removal', op: 'eq', value: true }],
          },
          calculationFormula: { fixedAmount: 5.00 },
          sortOrder: 1,
        },
      ],
    },

    // 11. Water Pumps (Product + Installation)
    {
      service: {
        id: 'srv_water_pumps',
        categoryId: 'cat_home_services',
        nameAr: 'مضخات مياه وبوستر',
        nameEn: 'Water Pumps & Pressure Boosters',
        descriptionAr: 'كتالوج مضخات مياه إيطالية ومضخات صامتة مع خيار التركيب ومعايرة الضغط',
        descriptionEn: 'Italian water pumps and silent booster systems with installation service',
        type: 'home_service',
        basePrice: '65.00',
        unitAr: 'مضخة',
        unitEn: 'pump',
        isLaborOnly: false,
        serviceMode: 'product_installation',
        status: 'published',
        isPublished: true,
        isActive: true,
        currentVersion: 1,
      },
      options: [
        {
          id: 'opt_pump_half_hp',
          nameAr: 'مضخة مياه نصف حصان إيطالي (Pedrollo)',
          nameEn: '0.5 HP Italian Pedrollo Water Pump',
          optionType: 'product',
          brand: 'Pedrollo',
          size: '0.5 HP',
          price: '65.00',
          installationPrice: '20.00',
          unitAr: 'مضخة',
          unitEn: 'pump',
          sortOrder: 1,
          isActive: true,
        },
        {
          id: 'opt_pump_one_hp_silent',
          nameAr: 'مضخة بوستر ذكية صامتة 1.0 حصان إنفيرتر',
          nameEn: '1.0 HP Smart Silent Booster Pump',
          optionType: 'product',
          brand: 'Shimge / Leo',
          size: '1.0 HP',
          price: '120.00',
          installationPrice: '25.00',
          unitAr: 'مضخة',
          unitEn: 'pump',
          sortOrder: 2,
          isActive: true,
        },
        {
          id: 'opt_pump_pressure_switch',
          nameAr: 'أوتوماتيك ضغط مياه إلكتروني (Press Control)',
          nameEn: 'Automatic Electronic Pressure Switch',
          optionType: 'product',
          brand: 'Italtecnica',
          price: '22.00',
          installationPrice: '10.00',
          unitAr: 'جهاز',
          unitEn: 'switch',
          sortOrder: 3,
          isActive: true,
        },
      ],
      fields: [
        {
          key: 'include_installation',
          labelAr: 'إضافة خدمة التركيب والتوصيل الكهربائي والمائي',
          labelEn: 'Include installation & electrical/plumbing connection',
          fieldType: 'toggle',
          defaultValue: true,
          isRequired: false,
          sortOrder: 1,
        },
      ],
      rules: [],
      pricingRules: [],
    },

    // 12. Water Tanks (Product + Installation)
    {
      service: {
        id: 'srv_water_tanks',
        categoryId: 'cat_home_services',
        nameAr: 'خزانات مياه بولي إيثيلين',
        nameEn: 'Water Storage Tanks',
        descriptionAr: 'خزانات مياه 4 طبقات معالجة ومقاومة للبكتيريا وأشعة الشمس مع التوصيل والرفع',
        descriptionEn: '4-layer antibacterial water tanks with delivery, rooftop hoisting and installation',
        type: 'home_service',
        basePrice: '90.00',
        unitAr: 'خزان',
        unitEn: 'tank',
        isLaborOnly: false,
        serviceMode: 'product_installation',
        status: 'published',
        isPublished: true,
        isActive: true,
        currentVersion: 1,
      },
      options: [
        {
          id: 'opt_tank_1m3',
          nameAr: 'خزان مياه 1 متر مكعب (1000 لتر) 4 طبقات',
          nameEn: '1m³ 4-Layer Antibacterial Tank',
          optionType: 'product',
          size: '1000 L',
          price: '90.00',
          installationPrice: '30.00',
          unitAr: 'خزان',
          unitEn: 'tank',
          sortOrder: 1,
          isActive: true,
        },
        {
          id: 'opt_tank_2m3',
          nameAr: 'خزان مياه 2 متر مكعب (2000 لتر) 4 طبقات',
          nameEn: '2m³ 4-Layer Heavy Duty Tank',
          optionType: 'product',
          size: '2000 L',
          price: '160.00',
          installationPrice: '40.00',
          unitAr: 'خزان',
          unitEn: 'tank',
          sortOrder: 2,
          isActive: true,
        },
      ],
      fields: [
        {
          key: 'include_installation',
          labelAr: 'إضافة الرفع للسطح والتركيب مع عوامة نحاس',
          labelEn: 'Include rooftop installation & brass float valve',
          fieldType: 'toggle',
          defaultValue: true,
          isRequired: false,
          sortOrder: 1,
        },
      ],
      rules: [],
      pricingRules: [],
    },

    // 13. Locks & Keys (Product + Installation)
    {
      service: {
        id: 'srv_locks_keys',
        categoryId: 'cat_home_services',
        nameAr: 'أقفال وكوالين ومفاتيح',
        nameEn: 'Locks, Handles & Smart Security',
        descriptionAr: 'أقفال أبواب أمان، سيلندرات نحاسية، أقفال ذكية ببصمة الإصبع مع التركيب الفوري',
        descriptionEn: 'Security cylinders, smart biometric locks, handles and locksmith services',
        type: 'home_service',
        basePrice: '18.00',
        unitAr: 'قفل',
        unitEn: 'lock',
        isLaborOnly: false,
        serviceMode: 'product_installation',
        status: 'published',
        isPublished: true,
        isActive: true,
        currentVersion: 1,
      },
      options: [
        {
          id: 'opt_lock_cylinder_high_sec',
          nameAr: 'سيلندر أمان نحاسي مع 5 مفاتيح كمبيوتر',
          nameEn: 'High Security Brass Cylinder (5 Keys)',
          optionType: 'product',
          brand: 'Yale / Cisa',
          price: '18.00',
          installationPrice: '10.00',
          unitAr: 'سيلندر',
          unitEn: 'cylinder',
          sortOrder: 1,
          isActive: true,
        },
        {
          id: 'opt_lock_smart_biometric',
          nameAr: 'قفل ذكي إلكتروني ببصمة الإصبع ورمز سري وبطاقة',
          nameEn: 'Smart Biometric Fingerprint & Code Lock',
          optionType: 'product',
          brand: 'Tuya Smart',
          price: '145.00',
          installationPrice: '35.00',
          unitAr: 'قفل ذكي',
          unitEn: 'smart lock',
          sortOrder: 2,
          isActive: true,
        },
        {
          id: 'opt_lock_handle_set',
          nameAr: 'طقم مسكات أبواب ستانلس ستيل تركي',
          nameEn: 'Stainless Steel Door Handle Set',
          optionType: 'product',
          brand: 'Kale',
          price: '28.00',
          installationPrice: '10.00',
          unitAr: 'طقم مسكات',
          unitEn: 'handle set',
          sortOrder: 3,
          isActive: true,
        },
      ],
      fields: [
        {
          key: 'include_installation',
          labelAr: 'إضافة خدمة التركيب والمعايرة الفورية',
          labelEn: 'Include on-site installation & calibration',
          fieldType: 'toggle',
          defaultValue: true,
          isRequired: false,
          sortOrder: 1,
        },
        {
          key: 'door_type',
          labelAr: 'نوع الباب',
          labelEn: 'Door Type',
          fieldType: 'select',
          options: [
            { id: 'wood', labelAr: 'خشب', labelEn: 'Wood', value: 'wood' },
            { id: 'armored', labelAr: 'مصفح / سيكيوريتي', labelEn: 'Armored Security', value: 'armored' },
            { id: 'aluminum', labelAr: 'ألمنيوم / زجاج', labelEn: 'Aluminum / Glass', value: 'aluminum' },
          ],
          defaultValue: 'wood',
          isRequired: false,
          sortOrder: 2,
        },
      ],
      rules: [],
      pricingRules: [],
    },

    // 14. Electrical Appliance Maintenance (Starting from 5 JOD)
    {
      service: {
        id: 'srv_appliance_maintenance',
        categoryId: 'cat_home_services',
        nameAr: 'صيانة الأجهزة المنزلية والكهربائية',
        nameEn: 'Home Appliances Maintenance',
        descriptionAr: 'صيانة وتصليح الميكروويف، الأفران، مبردات المياه، المكانس، والأجهزة المنزلية',
        descriptionEn: 'Repair and maintenance for ovens, microwaves, water dispensers, and home electronics',
        type: 'home_service',
        basePrice: '5.00',
        unitAr: 'أجرة معاينة/يد',
        unitEn: 'inspection/labor fee',
        startingPriceLabelAr: 'يبدأ من',
        startingPriceLabelEn: 'Starting from',
        disclaimerAr: 'السعر الظاهر هو أجرة اليد/الخدمة الأساسية فقط، ولا يشمل قطع الغيار أو المواد أو المعدات أو أي أعمال إضافية قد تكون مطلوبة.',
        disclaimerEn: 'The displayed price is the labor/service starting fee only. It does not include spare parts, materials, equipment, or additional work that may be required.',
        isLaborOnly: true,
        requiresQuotation: true,
        serviceMode: 'labor_inspection',
        status: 'published',
        isPublished: true,
        isActive: true,
        currentVersion: 1,
      },
      options: [],
      fields: [
        {
          key: 'appliance_type',
          labelAr: 'نوع الجهاز',
          labelEn: 'Appliance Type',
          fieldType: 'select',
          options: [
            { id: 'oven', labelAr: 'فرن غاز / كهرباء', labelEn: 'Gas/Electric Oven', value: 'oven' },
            { id: 'microwave', labelAr: 'ميكروويف', labelEn: 'Microwave', value: 'microwave' },
            { id: 'water_dispenser', labelAr: 'مبرد مياه (Cooler)', labelEn: 'Water Dispenser', value: 'water_dispenser' },
            { id: 'vacuum', labelAr: 'مكنسة كهربائية', labelEn: 'Vacuum Cleaner', value: 'vacuum' },
            { id: 'other', labelAr: 'جهاز آخر', labelEn: 'Other Appliance', value: 'other' },
          ],
          defaultValue: 'oven',
          isRequired: true,
          sortOrder: 1,
        },
        {
          key: 'problem_description',
          labelAr: 'وصف عطل الجهاز',
          labelEn: 'Problem Description',
          fieldType: 'textarea',
          isRequired: true,
          sortOrder: 2,
        },
        {
          key: 'appliance_photos',
          labelAr: 'صور الجهاز واللوحة الفنية (اختياري)',
          labelEn: 'Photos (optional)',
          fieldType: 'image_upload',
          isRequired: false,
          sortOrder: 3,
        },
      ],
      rules: [],
      pricingRules: [
        {
          ruleType: 'base',
          titleAr: 'أجرة اليد الأساسية',
          titleEn: 'Starting Labor Fee',
          calculationFormula: { fixedAmount: 5.00 },
          sortOrder: 1,
        },
      ],
    },

    // 15. Washing Machine Maintenance (Starting from 5 JOD)
    {
      service: {
        id: 'srv_washing_machines',
        categoryId: 'cat_home_services',
        nameAr: 'صيانة غسالات الملابس',
        nameEn: 'Washing Machine Repair',
        descriptionAr: 'صيانة غسالات أوتوماتيك وعادية، حل مشاكل العصر، تصريف المياه، صوت المحرك، والأعطال',
        descriptionEn: 'Automatic washing machine troubleshooting, spin cycle, drainage and motor repairs',
        type: 'home_service',
        basePrice: '5.00',
        unitAr: 'أجرة معاينة/يد',
        unitEn: 'inspection/labor fee',
        startingPriceLabelAr: 'يبدأ من',
        startingPriceLabelEn: 'Starting from',
        disclaimerAr: 'السعر الظاهر هو أجرة اليد/الخدمة الأساسية فقط، ولا يشمل قطع الغيار أو المواد أو المعدات أو أي أعمال إضافية قد تكون مطلوبة.',
        disclaimerEn: 'The displayed price is the labor/service starting fee only. It does not include spare parts, materials, equipment, or additional work that may be required.',
        isLaborOnly: true,
        requiresQuotation: true,
        serviceMode: 'labor_inspection',
        status: 'published',
        isPublished: true,
        isActive: true,
        currentVersion: 1,
      },
      options: [],
      fields: [
        {
          key: 'machine_type',
          labelAr: 'نوع الغسالة',
          labelEn: 'Machine Type',
          fieldType: 'select',
          options: [
            { id: 'front_load', labelAr: 'فل أوتوماتيك فتحة أمامية (Front Load)', labelEn: 'Front Load Automatic', value: 'front_load' },
            { id: 'top_load', labelAr: 'فل أوتوماتيك فتحة علوية (Top Load)', labelEn: 'Top Load Automatic', value: 'top_load' },
            { id: 'twin_tub', labelAr: 'نصف أوتوماتيك حوضين', labelEn: 'Twin Tub Semi-Auto', value: 'twin_tub' },
          ],
          defaultValue: 'front_load',
          isRequired: true,
          sortOrder: 1,
        },
        {
          key: 'problem_description',
          labelAr: 'وصف العطل بالتفصيل',
          labelEn: 'Problem Description',
          fieldType: 'textarea',
          placeholderAr: 'مثال: الغسالة لا تعصر وتصدر صوتاً عالياً...',
          isRequired: true,
          sortOrder: 2,
        },
        {
          key: 'photos',
          labelAr: 'صور العطل (اختياري)',
          labelEn: 'Photos (optional)',
          fieldType: 'image_upload',
          isRequired: false,
          sortOrder: 3,
        },
      ],
      rules: [],
      pricingRules: [
        {
          ruleType: 'base',
          titleAr: 'أجرة اليد الأساسية',
          titleEn: 'Starting Labor Fee',
          calculationFormula: { fixedAmount: 5.00 },
          sortOrder: 1,
        },
      ],
    },

    // 16. Dryer Maintenance (Starting from 5 JOD)
    {
      service: {
        id: 'srv_dryers',
        categoryId: 'cat_home_services',
        nameAr: 'صيانة نشافات الملابس',
        nameEn: 'Clothes Dryer Repair',
        descriptionAr: 'صيانة نشافات الملابس، فحص الهيتر، الحزام، تصريف المياه، ومشاكل عدم التجفيف',
        descriptionEn: 'Clothes dryer repair, heater element, belt, sensor and drainage troubleshooting',
        type: 'home_service',
        basePrice: '5.00',
        unitAr: 'أجرة معاينة/يد',
        unitEn: 'inspection/labor fee',
        startingPriceLabelAr: 'يبدأ من',
        startingPriceLabelEn: 'Starting from',
        disclaimerAr: 'السعر الظاهر هو أجرة اليد/الخدمة الأساسية فقط، ولا يشمل قطع الغيار أو المواد أو المعدات أو أي أعمال إضافية قد تكون مطلوبة.',
        disclaimerEn: 'The displayed price is the labor/service starting fee only. It does not include spare parts, materials, equipment, or additional work that may be required.',
        isLaborOnly: true,
        requiresQuotation: true,
        serviceMode: 'labor_inspection',
        status: 'published',
        isPublished: true,
        isActive: true,
        currentVersion: 1,
      },
      options: [],
      fields: [
        {
          key: 'problem_description',
          labelAr: 'وصف عطل النشافة',
          labelEn: 'Dryer Problem Description',
          fieldType: 'textarea',
          isRequired: true,
          sortOrder: 1,
        },
      ],
      rules: [],
      pricingRules: [
        {
          ruleType: 'base',
          titleAr: 'أجرة اليد الأساسية',
          titleEn: 'Starting Labor Fee',
          calculationFormula: { fixedAmount: 5.00 },
          sortOrder: 1,
        },
      ],
    },

    // 17. Refrigerator Maintenance (Starting from 5 JOD)
    {
      service: {
        id: 'srv_refrigerators',
        categoryId: 'cat_home_services',
        nameAr: 'صيانة ثلاجات',
        nameEn: 'Refrigerator Repair',
        descriptionAr: 'صيانة الثلاجات المنزلية، تعبئة غاز التبريد، تصليح الكمبروسر، وإصلاح مشاكل التبريد والتجميد',
        descriptionEn: 'Refrigerator maintenance, refrigerant refill, compressor repair and temperature issues',
        type: 'home_service',
        basePrice: '5.00',
        unitAr: 'أجرة معاينة/يد',
        unitEn: 'inspection/labor fee',
        startingPriceLabelAr: 'يبدأ من',
        startingPriceLabelEn: 'Starting from',
        disclaimerAr: 'السعر الظاهر هو أجرة اليد/الخدمة الأساسية فقط، ولا يشمل قطع الغيار أو المواد أو المعدات أو أي أعمال إضافية قد تكون مطلوبة.',
        disclaimerEn: 'The displayed price is the labor/service starting fee only. It does not include spare parts, materials, equipment, or additional work that may be required.',
        isLaborOnly: true,
        requiresQuotation: true,
        serviceMode: 'labor_inspection',
        status: 'published',
        isPublished: true,
        isActive: true,
        currentVersion: 1,
      },
      options: [],
      fields: [
        {
          key: 'problem_description',
          labelAr: 'وصف عطل الثلاجة بالتفصيل',
          labelEn: 'Refrigerator Problem Description',
          fieldType: 'textarea',
          isRequired: true,
          sortOrder: 1,
        },
      ],
      rules: [],
      pricingRules: [
        {
          ruleType: 'base',
          titleAr: 'أجرة اليد الأساسية',
          titleEn: 'Starting Labor Fee',
          calculationFormula: { fixedAmount: 5.00 },
          sortOrder: 1,
        },
      ],
    },

    // 18. Freezer Maintenance (Starting from 5 JOD)
    {
      service: {
        id: 'srv_freezers',
        categoryId: 'cat_home_services',
        nameAr: 'صيانة فريزرات',
        nameEn: 'Freezer Repair',
        descriptionAr: 'صيانة فريزرات الصندوق والفريزرات العمودية وشحن غاز وفحص الحساسات',
        descriptionEn: 'Chest and upright freezer repair, gas recharge and temperature sensors',
        type: 'home_service',
        basePrice: '5.00',
        unitAr: 'أجرة معاينة/يد',
        unitEn: 'inspection/labor fee',
        startingPriceLabelAr: 'يبدأ من',
        startingPriceLabelEn: 'Starting from',
        disclaimerAr: 'السعر الظاهر هو أجرة اليد/الخدمة الأساسية فقط، ولا يشمل قطع الغيار أو المواد أو المعدات أو أي أعمال إضافية قد تكون مطلوبة.',
        disclaimerEn: 'The displayed price is the labor/service starting fee only. It does not include spare parts, materials, equipment, or additional work that may be required.',
        isLaborOnly: true,
        requiresQuotation: true,
        serviceMode: 'labor_inspection',
        status: 'published',
        isPublished: true,
        isActive: true,
        currentVersion: 1,
      },
      options: [],
      fields: [
        {
          key: 'problem_description',
          labelAr: 'وصف عطل الفريزر',
          labelEn: 'Freezer Problem Description',
          fieldType: 'textarea',
          isRequired: true,
          sortOrder: 1,
        },
      ],
      rules: [],
      pricingRules: [
        {
          ruleType: 'base',
          titleAr: 'أجرة اليد الأساسية',
          titleEn: 'Starting Labor Fee',
          calculationFormula: { fixedAmount: 5.00 },
          sortOrder: 1,
        },
      ],
    },

    // 19. Sofa & Fabric Cleaning
    {
      service: {
        id: 'srv_sofa_cleaning',
        categoryId: 'cat_home_services',
        nameAr: 'غسيل وتعقيم كنب وسجاد',
        nameEn: 'Sofa & Carpet Deep Cleaning',
        descriptionAr: 'غسيل الكنب، السجاد، الموكيت، والفرشات بالبخار الحار وحقن الرغوة الجافة في الموقع',
        descriptionEn: 'On-site hot steam and dry injection sofa, carpet and mattress cleaning',
        type: 'home_service',
        basePrice: '15.00',
        unitAr: 'طقم كنب',
        unitEn: 'sofa set',
        isLaborOnly: false,
        serviceMode: 'dynamic_form',
        status: 'published',
        isPublished: true,
        isActive: true,
        currentVersion: 1,
      },
      options: [],
      fields: [
        {
          key: 'seats_count',
          labelAr: 'عدد مقاعد الكنب (Seats)',
          labelEn: 'Sofa Seats Count',
          fieldType: 'counter',
          min: '1',
          max: '20',
          step: '1',
          defaultValue: 5,
          isRequired: true,
          sortOrder: 1,
        },
        {
          key: 'steam_sanitize',
          labelAr: 'إضافة تعقيم فائق بالبخار وإزالة الروائح والبقع المستعصية (+5 د.أ)',
          labelEn: 'Include deep steam sanitize (+5 JOD)',
          fieldType: 'toggle',
          defaultValue: true,
          isRequired: false,
          sortOrder: 2,
        },
      ],
      rules: [],
      pricingRules: [
        {
          ruleType: 'field_multiplier',
          titleAr: 'أجرة غسيل المقاعد',
          titleEn: 'Seats Washing Fee',
          targetField: 'seats_count',
          calculationFormula: { ratePerUnit: 3.00, baseThreshold: 0 },
          sortOrder: 1,
        },
        {
          ruleType: 'conditional_formula',
          titleAr: 'رسوم التعقيم بالبخار',
          titleEn: 'Steam Sanitize Fee',
          condition: {
            operator: 'AND',
            expressions: [{ field: 'steam_sanitize', op: 'eq', value: true }],
          },
          calculationFormula: { fixedAmount: 5.00 },
          sortOrder: 2,
        },
      ],
    },

    // 20. Pest Control
    {
      service: {
        id: 'srv_pest_control',
        categoryId: 'cat_home_services',
        nameAr: 'مكافحة الحشرات والقوارض',
        nameEn: 'Pest & Rodent Control',
        descriptionAr: 'رش ومكافحة حشرات آمنة للمنازل والمطاعم، رش جل ألماني ومبيدات عديمة الرائحة مع الضمان',
        descriptionEn: 'Safe, odorless home pest extermination, gel injection and rodent control with warranty',
        type: 'home_service',
        basePrice: '25.00',
        unitAr: 'شقة / فيلا',
        unitEn: 'facility',
        isLaborOnly: false,
        serviceMode: 'dynamic_form',
        status: 'published',
        isPublished: true,
        isActive: true,
        currentVersion: 1,
      },
      options: [],
      fields: [
        {
          key: 'property_size',
          labelAr: 'حجم ونوع العقار',
          labelEn: 'Property Type & Size',
          fieldType: 'select',
          options: [
            { id: 'apt_small', labelAr: 'شقة صغيرة (أقل من 120م²)', labelEn: 'Small Apartment (<120m²)', value: 'apt_small' },
            { id: 'apt_large', labelAr: 'شقة كبيرة (120م² - 250م²)', labelEn: 'Large Apartment (120-250m²)', value: 'apt_large', priceModifier: 10.0 },
            { id: 'villa', labelAr: 'فيلا مستقلة مع حديقة', labelEn: 'Villa with Garden', value: 'villa', priceModifier: 25.0 },
          ],
          defaultValue: 'apt_small',
          isRequired: true,
          sortOrder: 1,
        },
      ],
      rules: [],
      pricingRules: [
        {
          ruleType: 'base',
          titleAr: 'الرسوم الأساسية لمكافحة الحشرات',
          titleEn: 'Base Pest Control Fee',
          calculationFormula: { fixedAmount: 25.00 },
          sortOrder: 1,
        },
      ],
    },

    // 21. Furniture Moving (Full Dynamic Engine)
    {
      service: {
        id: 'srv_furniture_moving',
        categoryId: 'cat_home_services',
        nameAr: 'نقل وترحيل أثاث',
        nameEn: 'Furniture Moving & Relocation',
        descriptionAr: 'نقل الأثاث بشاحنات مغلقة مجهزة، عمالة مدربة، ونش رفع هيدروليكي، وتغليف احترافي',
        descriptionEn: 'Professional furniture relocation with enclosed trucks, packing, dismantling and assembly',
        type: 'home_service',
        basePrice: '30.00',
        unitAr: 'نقلة أثاث',
        unitEn: 'move',
        isLaborOnly: false,
        serviceMode: 'dynamic_form',
        status: 'published',
        isPublished: true,
        isActive: true,
        currentVersion: 1,
      },
      options: [],
      fields: [
        {
          key: 'truck_size',
          labelAr: 'حجم شاحنة النقل',
          labelEn: 'Truck Size',
          fieldType: 'select',
          options: [
            { id: 'small', labelAr: 'شاحنة صغيرة (ديانا 3.5 طن)', labelEn: 'Small Truck (3.5T)', value: 'small' },
            { id: 'medium', labelAr: 'شاحنة متوسطة (ديانا 5 طن) (+10 د.أ)', labelEn: 'Medium Truck (5T) (+10 JOD)', value: 'medium', priceModifier: 10.0 },
            { id: 'large', labelAr: 'شاحنة كبيرة مغلقة (7 طن) (+20 د.أ)', labelEn: 'Large Box Truck (7T) (+20 JOD)', value: 'large', priceModifier: 20.0 },
          ],
          defaultValue: 'small',
          isRequired: true,
          sortOrder: 1,
        },
        {
          key: 'workers_count',
          labelAr: 'عدد عمال النقل والتنزيل',
          labelEn: 'Movers Count',
          fieldType: 'counter',
          min: '2',
          max: '8',
          step: '1',
          defaultValue: 2,
          isRequired: true,
          sortOrder: 2,
        },
        {
          key: 'pickup_floor',
          labelAr: 'طابق التحميل (من)',
          labelEn: 'Pickup Floor',
          fieldType: 'counter',
          min: '0',
          max: '12',
          step: '1',
          defaultValue: 1,
          isRequired: true,
          sortOrder: 3,
        },
        {
          key: 'has_elevator',
          labelAr: 'يتوفر مصعد يتسع للأثاث',
          labelEn: 'Elevator Available',
          fieldType: 'toggle',
          defaultValue: true,
          isRequired: false,
          sortOrder: 4,
        },
        {
          key: 'include_packing',
          labelAr: 'تغليف احترافي للأثاث بالكرتون والنايلون الفقاعي (+15 د.أ)',
          labelEn: 'Include professional packing (+15 JOD)',
          fieldType: 'toggle',
          defaultValue: false,
          isRequired: false,
          sortOrder: 5,
        },
        {
          key: 'dismantle_assembly',
          labelAr: 'فك وتركيب غرف النوم والخزائن (+20 د.أ)',
          labelEn: 'Dismantle and assemble bedroom furniture (+20 JOD)',
          fieldType: 'toggle',
          defaultValue: false,
          isRequired: false,
          sortOrder: 6,
        },
      ],
      rules: [],
      pricingRules: [
        {
          ruleType: 'base',
          titleAr: 'سعر النقل الأساسي (شاحنة وعاملين)',
          titleEn: 'Base Moving Fee (Truck & 2 Movers)',
          calculationFormula: { fixedAmount: 30.00 },
          sortOrder: 1,
        },
        {
          ruleType: 'field_multiplier',
          titleAr: 'أجرة عمال إضافيين',
          titleEn: 'Extra Movers Fee',
          targetField: 'workers_count',
          calculationFormula: { ratePerUnit: 5.00, baseThreshold: 2 },
          sortOrder: 2,
        },
        {
          ruleType: 'conditional_formula',
          titleAr: 'رسوم التغليف الاحترافي',
          titleEn: 'Packing Service Fee',
          condition: {
            operator: 'AND',
            expressions: [{ field: 'include_packing', op: 'eq', value: true }],
          },
          calculationFormula: { fixedAmount: 15.00 },
          sortOrder: 3,
        },
        {
          ruleType: 'conditional_formula',
          titleAr: 'رسوم فك وتركيب الأثاث',
          titleEn: 'Dismantle & Assembly Fee',
          condition: {
            operator: 'AND',
            expressions: [{ field: 'dismantle_assembly', op: 'eq', value: true }],
          },
          calculationFormula: { fixedAmount: 20.00 },
          sortOrder: 4,
        },
      ],
    },

    // 22. Painting (Starting from 5 JOD)
    {
      service: {
        id: 'srv_painting',
        categoryId: 'cat_home_services',
        nameAr: 'دهان وديكورات داخلية وخارجية',
        nameEn: 'Painting & Wall Decor',
        descriptionAr: 'دهان الجدران، معالجة الرطوبة والتشققات، دهان أبواب، وديكورات دهان حديثة',
        descriptionEn: 'Interior and exterior house painting, damp proofing, and decorative finishes',
        type: 'home_service',
        basePrice: '5.00',
        unitAr: 'أجرة معاينة/يد',
        unitEn: 'inspection/labor fee',
        startingPriceLabelAr: 'يبدأ من',
        startingPriceLabelEn: 'Starting from',
        disclaimerAr: 'السعر الظاهر هو أجرة اليد/الخدمة الأساسية فقط، ولا يشمل قطع الغيار أو المواد أو المعدات أو أي أعمال إضافية قد تكون مطلوبة.',
        disclaimerEn: 'The displayed price is the labor/service starting fee only. It does not include spare parts, materials, equipment, or additional work that may be required.',
        isLaborOnly: true,
        requiresQuotation: true,
        serviceMode: 'labor_inspection',
        status: 'published',
        isPublished: true,
        isActive: true,
        currentVersion: 1,
      },
      options: [],
      fields: [
        {
          key: 'rooms_count',
          labelAr: 'عدد الغرف التقريبي',
          labelEn: 'Approximate Rooms Count',
          fieldType: 'counter',
          min: '1',
          max: '15',
          step: '1',
          defaultValue: 1,
          isRequired: true,
          sortOrder: 1,
        },
        {
          key: 'problem_description',
          labelAr: 'تفاصيل أعمال الدهان المطلوبة',
          labelEn: 'Painting Job Description',
          fieldType: 'textarea',
          isRequired: true,
          sortOrder: 2,
        },
      ],
      rules: [],
      pricingRules: [
        {
          ruleType: 'base',
          titleAr: 'أجرة اليد الأساسية',
          titleEn: 'Starting Labor Fee',
          calculationFormula: { fixedAmount: 5.00 },
          sortOrder: 1,
        },
      ],
    },

    // 23. Tiling (Starting from 5 JOD)
    {
      service: {
        id: 'srv_tiling',
        categoryId: 'cat_home_services',
        nameAr: 'تبليط وسيراميك وباركيه',
        nameEn: 'Tiling & Flooring Services',
        descriptionAr: 'تركيب وصيانة السيراميك، البورسلان، الرخام، الباركيه، ومعالجة فواصل البلاط',
        descriptionEn: 'Ceramic, porcelain, marble and parquet installation and grouting repairs',
        type: 'home_service',
        basePrice: '5.00',
        unitAr: 'أجرة معاينة/يد',
        unitEn: 'inspection/labor fee',
        startingPriceLabelAr: 'يبدأ من',
        startingPriceLabelEn: 'Starting from',
        disclaimerAr: 'السعر الظاهر هو أجرة اليد/الخدمة الأساسية فقط، ولا يشمل قطع الغيار أو المواد أو المعدات أو أي أعمال إضافية قد تكون مطلوبة.',
        disclaimerEn: 'The displayed price is the labor/service starting fee only. It does not include spare parts, materials, equipment, or additional work that may be required.',
        isLaborOnly: true,
        requiresQuotation: true,
        serviceMode: 'labor_inspection',
        status: 'published',
        isPublished: true,
        isActive: true,
        currentVersion: 1,
      },
      options: [],
      fields: [
        {
          key: 'problem_description',
          labelAr: 'تفاصيل ومساحة أعمال التبليط المطلوبة',
          labelEn: 'Tiling Job Details & Area',
          fieldType: 'textarea',
          isRequired: true,
          sortOrder: 1,
        },
      ],
      rules: [],
      pricingRules: [
        {
          ruleType: 'base',
          titleAr: 'أجرة اليد الأساسية',
          titleEn: 'Starting Labor Fee',
          calculationFormula: { fixedAmount: 5.00 },
          sortOrder: 1,
        },
      ],
    },

    // 24. Glass & Aluminum (Starting from 5 JOD)
    {
      service: {
        id: 'srv_glass_aluminum',
        categoryId: 'cat_home_services',
        nameAr: 'ألمنيوم وزجاج وشبابيك',
        nameEn: 'Aluminum & Glass Works',
        descriptionAr: 'صيانة وتفصيل شبابيك الألمنيوم، كبائن الشاور، تبديل زجاج مكسور، وتركيب مناخل الحشرات',
        descriptionEn: 'Aluminum window repair, shower cabins, broken glass replacement and insect mesh',
        type: 'home_service',
        basePrice: '5.00',
        unitAr: 'أجرة معاينة/يد',
        unitEn: 'inspection/labor fee',
        startingPriceLabelAr: 'يبدأ من',
        startingPriceLabelEn: 'Starting from',
        disclaimerAr: 'السعر الظاهر هو أجرة اليد/الخدمة الأساسية فقط، ولا يشمل قطع الغيار أو المواد أو المعدات أو أي أعمال إضافية قد تكون مطلوبة.',
        disclaimerEn: 'The displayed price is the labor/service starting fee only. It does not include spare parts, materials, equipment, or additional work that may be required.',
        isLaborOnly: true,
        requiresQuotation: true,
        serviceMode: 'labor_inspection',
        status: 'published',
        isPublished: true,
        isActive: true,
        currentVersion: 1,
      },
      options: [],
      fields: [
        {
          key: 'problem_description',
          labelAr: 'تفاصيل العمل المطلوب',
          labelEn: 'Work Description',
          fieldType: 'textarea',
          isRequired: true,
          sortOrder: 1,
        },
      ],
      rules: [],
      pricingRules: [
        {
          ruleType: 'base',
          titleAr: 'أجرة اليد الأساسية',
          titleEn: 'Starting Labor Fee',
          calculationFormula: { fixedAmount: 5.00 },
          sortOrder: 1,
        },
      ],
    },

    // 25. TV & Shelves Mounting
    {
      service: {
        id: 'srv_mounting',
        categoryId: 'cat_home_services',
        nameAr: 'تركيب شاشات ورفوف وبراويز',
        nameEn: 'TV & Shelves Mounting',
        descriptionAr: 'تثبيت وتركيب شاشات التلفزيون، الرفوف الديكورية، المرايا الثقيلة، وقضبان الستائر بميزان ليزر',
        descriptionEn: 'Professional wall mounting for TVs, decorative shelves, heavy mirrors and curtain rods',
        type: 'home_service',
        basePrice: '10.00',
        unitAr: 'قطعة',
        unitEn: 'item',
        isLaborOnly: false,
        serviceMode: 'dynamic_form',
        status: 'published',
        isPublished: true,
        isActive: true,
        currentVersion: 1,
      },
      options: [],
      fields: [
        {
          key: 'items_count',
          labelAr: 'عدد القطع المطلوب تثبيتها',
          labelEn: 'Number of Items to Mount',
          fieldType: 'counter',
          min: '1',
          max: '10',
          step: '1',
          defaultValue: 1,
          isRequired: true,
          sortOrder: 1,
        },
        {
          key: 'has_bracket',
          labelAr: 'حامل الشاشة متوفر لديك مسبقاً',
          labelEn: 'TV wall bracket is already available',
          fieldType: 'toggle',
          defaultValue: true,
          isRequired: false,
          sortOrder: 2,
        },
      ],
      rules: [],
      pricingRules: [
        {
          ruleType: 'base',
          titleAr: 'أجرة تركيب القطعة الأولى',
          titleEn: 'First Item Mounting Fee',
          calculationFormula: { fixedAmount: 10.00 },
          sortOrder: 1,
        },
        {
          ruleType: 'field_multiplier',
          titleAr: 'أجرة تركيب قطع إضافية',
          titleEn: 'Extra Items Mounting Fee',
          targetField: 'items_count',
          calculationFormula: { ratePerUnit: 5.00, baseThreshold: 1 },
          sortOrder: 2,
        },
        {
          ruleType: 'conditional_formula',
          titleAr: 'توفير حامل شاشة أصلي متحرك',
          titleEn: 'Provide TV Wall Bracket',
          condition: {
            operator: 'AND',
            expressions: [{ field: 'has_bracket', op: 'eq', value: false }],
          },
          calculationFormula: { fixedAmount: 12.00 },
          sortOrder: 3,
        },
      ],
    },

    // 26. Other Configurable Home Services
    {
      service: {
        id: 'srv_other_services',
        categoryId: 'cat_home_services',
        nameAr: 'خدمات منزلية أخرى مخصصة',
        nameEn: 'Custom Home Services',
        descriptionAr: 'لأي خدمات أو أعمال صيانة لم تجدها في القائمة، اطلب المعاينة وسنقوم بتوفير الفني المناسب',
        descriptionEn: 'Custom on-demand home maintenance and specialized inspection requests',
        type: 'home_service',
        basePrice: '5.00',
        unitAr: 'أجرة معاينة/يد',
        unitEn: 'inspection/labor fee',
        startingPriceLabelAr: 'يبدأ من',
        startingPriceLabelEn: 'Starting from',
        disclaimerAr: 'السعر الظاهر هو أجرة اليد/الخدمة الأساسية فقط، ولا يشمل قطع الغيار أو المواد أو المعدات أو أي أعمال إضافية قد تكون مطلوبة.',
        disclaimerEn: 'The displayed price is the labor/service starting fee only. It does not include spare parts, materials, equipment, or additional work that may be required.',
        isLaborOnly: true,
        requiresQuotation: true,
        serviceMode: 'labor_inspection',
        status: 'published',
        isPublished: true,
        isActive: true,
        currentVersion: 1,
      },
      options: [],
      fields: [
        {
          key: 'service_title',
          labelAr: 'عنوان الخدمة أو العمل المطلوب',
          labelEn: 'Service Title',
          fieldType: 'text',
          isRequired: true,
          sortOrder: 1,
        },
        {
          key: 'problem_description',
          labelAr: 'شرح مفصل للطلب',
          labelEn: 'Detailed Request Description',
          fieldType: 'textarea',
          isRequired: true,
          sortOrder: 2,
        },
      ],
      rules: [],
      pricingRules: [
        {
          ruleType: 'base',
          titleAr: 'أجرة اليد الأساسية',
          titleEn: 'Starting Labor Fee',
          calculationFormula: { fixedAmount: 5.00 },
          sortOrder: 1,
        },
      ],
    },
  ];

  for (const def of catalogDefinitions) {
    const srv = def.service;

    // Check if service already exists
    const [existing] = await db.select().from(services).where(eq(services.id, srv.id)).limit(1);
    if (!existing) {
      await db.insert(services).values({
        ...srv,
        providerId: defaultProviderId || null,
      });
    } else {
      await db
        .update(services)
        .set({
          startingPriceLabelAr: srv.startingPriceLabelAr || 'يبدأ من',
          startingPriceLabelEn: srv.startingPriceLabelEn || 'Starting from',
          disclaimerAr: srv.disclaimerAr || '',
          disclaimerEn: srv.disclaimerEn || '',
          isLaborOnly: srv.isLaborOnly || false,
          serviceMode: srv.serviceMode || 'dynamic_form',
          requiresQuotation: srv.requiresQuotation || false,
          updatedAt: new Date(),
        })
        .where(eq(services.id, srv.id));
    }

    // Insert options
    if (def.options && def.options.length > 0) {
      for (const opt of def.options) {
        const [optExist] = await db.select().from(serviceOptions).where(eq(serviceOptions.id, opt.id)).limit(1);
        if (!optExist) {
          await db.insert(serviceOptions).values({
            ...opt,
            serviceId: srv.id,
          });
        }
      }
    }

    // Insert fields
    if (def.fields && def.fields.length > 0) {
      for (let i = 0; i < def.fields.length; i++) {
        const fld = def.fields[i];
        const fldId = `fld_${srv.id}_${fld.key}`;
        const [fldExist] = await db.select().from(serviceFields).where(eq(serviceFields.id, fldId)).limit(1);
        if (!fldExist) {
          await db.insert(serviceFields).values({
            id: fldId,
            serviceId: srv.id,
            key: fld.key,
            labelAr: fld.labelAr,
            labelEn: fld.labelEn,
            fieldType: fld.fieldType,
            defaultValue: fld.defaultValue !== undefined ? fld.defaultValue : null,
            min: fld.min || null,
            max: fld.max || null,
            step: fld.step || null,
            unitAr: fld.unitAr || null,
            unitEn: fld.unitEn || null,
            options: fld.options || [],
            isRequired: fld.isRequired || false,
            sortOrder: fld.sortOrder || i,
            isActive: true,
          });
        }
      }
    }

    // Insert pricing rules
    if (def.pricingRules && def.pricingRules.length > 0) {
      for (let i = 0; i < def.pricingRules.length; i++) {
        const pr = def.pricingRules[i];
        const prId = `prc_${srv.id}_${i}`;
        const [prExist] = await db.select().from(servicePricingRules).where(eq(servicePricingRules.id, prId)).limit(1);
        if (!prExist) {
          await db.insert(servicePricingRules).values({
            id: prId,
            serviceId: srv.id,
            ruleType: pr.ruleType,
            titleAr: pr.titleAr,
            titleEn: pr.titleEn,
            targetField: pr.targetField || null,
            calculationFormula: pr.calculationFormula || {},
            condition: pr.condition || null,
            sortOrder: pr.sortOrder || i,
            isActive: true,
          });
        }
      }
    }

    // Link service to active providers in provider_services if not already linked
    if (activeProviders.length > 0) {
      for (const prov of activeProviders) {
        const [linkExist] = await db
          .select()
          .from(providerServices)
          .where(eq(providerServices.serviceId, srv.id))
          .limit(1);
        if (!linkExist) {
          await db
            .insert(providerServices)
            .values({
              providerId: prov.id,
              serviceId: srv.id,
              isAvailable: true,
            })
            .onConflictDoNothing();
        }
      }
    }
  }

  console.log('✅ [PHASE 4 CATALOG] All 26 services successfully created and linked to providers.');
}

if (process.argv[1]?.endsWith('init_phase4_catalog.ts')) {
  initPhase4Catalog()
    .then(() => process.exit(0))
    .catch((err) => {
      console.error('❌ Error initializing catalog:', err);
      process.exit(1);
    });
}
