import { User, UserRole, Permission } from '../types';

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  super_admin: [
    'view_dashboard',
    'view_orders',
    'manage_orders',
    'view_customers',
    'manage_customers',
    'view_customer_history',
    'manage_customer_service',
    'create_customer_notes',
    'create_support_case',
    'view_support_cases',
    'manage_support_cases',
    'contact_customer',
    'update_order_support_status',
    'request_refunds',
    'review_refunds',
    'approve_refunds',
    'execute_refunds',
    'view_refund_history',
    'view_staff_activity',
    'view_customer_service_analytics',
    'manage_staff',
    'manage_roles',
    'manage_permissions',
    'view_audit_logs',
    'view_analytics',
    'view_providers',
    'manage_providers',
    'view_delivery',
    'manage_delivery',
    'manage_services',
    'manage_coupons',
    'manage_offers',
    'manage_settings',
  ],
  admin: [
    'view_dashboard',
    'view_orders',
    'manage_orders',
    'view_customers',
    'manage_customers',
    'view_customer_history',
    'manage_customer_service',
    'create_customer_notes',
    'create_support_case',
    'view_support_cases',
    'manage_support_cases',
    'contact_customer',
    'update_order_support_status',
    'request_refunds',
    'review_refunds',
    'approve_refunds',
    'execute_refunds',
    'view_refund_history',
    'view_staff_activity',
    'view_customer_service_analytics',
    'manage_staff',
    'manage_roles',
    'manage_permissions',
    'view_audit_logs',
    'view_analytics',
    'view_providers',
    'manage_providers',
    'view_delivery',
    'manage_delivery',
    'manage_services',
    'manage_coupons',
    'manage_offers',
    'manage_settings',
  ],
  customer_service_manager: [
    'view_dashboard',
    'view_orders',
    'manage_orders',
    'view_customers',
    'view_customer_history',
    'manage_customer_service',
    'create_customer_notes',
    'create_support_case',
    'view_support_cases',
    'manage_support_cases',
    'contact_customer',
    'update_order_support_status',
    'request_refunds',
    'review_refunds',
    'approve_refunds',
    'view_refund_history',
    'view_staff_activity',
    'view_customer_service_analytics',
    'view_audit_logs',
    'view_providers',
    'view_delivery',
  ],
  customer_service_agent: [
    'view_dashboard',
    'view_orders',
    'view_customers',
    'view_customer_history',
    'create_customer_notes',
    'create_support_case',
    'view_support_cases',
    'contact_customer',
    'update_order_support_status',
    'request_refunds',
    'view_refund_history',
  ],
  customer: [],
  delivery: [],
  provider: [],
};

export const hasPermission = (user: User | null, permission: Permission): boolean => {
  if (!user) return false;
  const permissions = ROLE_PERMISSIONS[user.role];
  return permissions ? permissions.includes(permission) : false;
};

export const isStaffUser = (user: User | null): boolean => {
  if (!user) return false;
  return ['super_admin', 'admin', 'customer_service_manager', 'customer_service_agent'].includes(user.role);
};
